name: Tests build and push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          pip install poetry==1.1.15

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        run: |
          make test

      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          ignore: DL3008,SC3009,DL3013

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        # do this step only on push to main and do not run for pull request
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          # push to registry when merge to main
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/arm64
          no-cache: true
          tags: 
            - ghcr.io/yurnov/electricitybot:latest
            - ghcr.io/yurnov/electricitybot:${{ github.sha }}
